
spring:
  application:
    name: demo
  #DB
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  #h2
  h2:
    console:
      enabled: true
  #saml
  security:
    saml2:
      relyingparty:
        registration:
          my-client: #任意の値
            entity-id: spring-saml-demo #ここで指定した値がkeycloakのクライアントIDとなる
            signing:
              credentials:
                - private-key-location: classpath:credentials/local.key #生成した秘密鍵と証明書を指定
                  certificate-location: classpath:credentials/local.crt #ファイルはsrc/main/resources/credentialsに配置しておく
            assertingparty:
              # keycloakのmetadataを取得するためのURL
              # [keycloakホスト]/realms/[レルム名]/protocol/saml/descriptor
              metadata-uri: http://localhost:18080/realms/demo/protocol/saml/descriptor

#LOG
logging:
  level:
    org:
      springframework.web: debug

#Mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true